
# Site settings

url: "http://ggallohernandez.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

#baseurl: /ggallohernandez.com.ar

google-tracking-id: "<YOUR GOOGLE TRACKING ID>"

#############
# HTML Head #
#############

author: "Luis Guillermo Gallo Hernández"
lang: "es"
title: "ggallohernandez"
favicon: "/img/favicon.ico"
description: "Sitio personal de Luis Guillermo Gallo Hernández."
keywords: "gallo, hernández, luis, guillermo, ggallohernandez, personal, sitio, cv, curriculum"

################
# Intro layout #
################

black-favicon: "/img/black-lab-glass.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/perfil.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: False
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	0		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Para entender lo que es la recursividad, hay que entender primero lo que es la recursividad."
  - text: "PHP es un mal menor perpetrado y creado por amateurs incompetentes, mientras que Perl es un gran e insidioso mal perpetrado por hábiles pero pervertidos profesionales -- Jon Ribbens"
  - text: "Los ordenadores son inútiles. Sólo pueden darte respuestas -- Pablo Picasso"
  - text: "Preguntarse cuándo los ordenadores podrán pensar es como preguntarse cuándo los submarinos podrán nadar -- Edsger W. Dijkstra"
  - text: "El buen código es su mejor documentación -- Steve McConnell"
  - text: "Siempre deseé que mi computadora fuera tan fácil de usar como mi teléfono. Mi deseo se ha hecho realidad: ya no sé usar mi teléfono. -- Bjarne Stroustrup"

########
# Blog #
########

post-preview-words: 128

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "ggallohernandez"

###############
# Life Events #
###############

events:
  - image: "/img/empresa/promaker.jpg"
    date: "Noviembre 2014 - Actualidad"
    title: "Director de Desarrollo de Sistemas en Promaker SRL"
    description: "Líder de equipo de desarrollo, gestión del departamento de desarrollo de sistemas, y análisis de proyectos"
  - image: "/img/empresa/promaker.jpg"
    date: "Junio 2013 - Noviembre 2014"
    title: "Desarrollador PHP Semi-Senior en Promaker SRL"
    description: "Desarrollo y mantenimientos de sitios web, intranets y sistemas de reporting en plataforma LAMP, utilizando framework Codeigniter."
  - image: "/img/empresa/municipalidad_esteban_echeverria.png"
    date: "Junio 2012 - Agosto 2013"
    title: "Desarrollador PHP Semi-Senior en Municipalidad de Esteban Echeverria"
    description: "Desarrollo de aplicación web para la generación de declaraciones juradas para la Tasa de Seguridad e Higiene y su volante de pago correspondiente con código de barras de Pago Fácil Y Banco Provincia. Desarrollo de sistema web de turnos para la dirección de licencias, panel de administración y sistemas internos."
  - image: "/img/empresa/tmt.jpg"
    date: "Enero 2012 - Julio 2012"
    title: "Desarrollador PHP Junior en TMT SRL"
    description: "Desarrollo de sistemas de web reporting, en plataforma LAMP, utilizando framework Symfony y Codeigniter"
  - image: "/img/empresa/municipalidad_esteban_echeverria.png"
    date: "Febrero 2011 - Enero 2012"
    title: "Desarrollador PHP Junior en Municipalidad de Esteban Echeverria"
    description: "Desarrollo de sistemas de gestion internos, y de reporting en plataforma LAMP, utilizando framework CakePHP"

# First image of the Career timeline
career-img: "/img/empresa/default.png"

studies:
  - image: "/img/institucion/unlam.png"
    date: "Abril 2009 - Actualidad"
    title: "Ingeniería en Informática"
    description: "Universidad Nacional de La Matanza"

studies-img: "/img/empresa/default.png"

services:
  - title: "Programación orientada a objetos"
    tags: ['desing-patterns', 'oop', 'clean-code']
    description: "Buenas prácticas de desarrollo orientado a objetos, utilización de patrones de diseño." 
  - title: "PHP5"
    tags: ['php5']
    description: "Sólido conocimiento del lenguaje PHP, y sus versiones más modernas." 
  - title: "Desarrollo web"
    tags: ['html5', 'css3', 'javascript', 'jquery', 'caching', 'security']
    description: "Experiencia en desarrollo de sistemas web, como sitios, intranets y sistemas de reporting. Utilización de metodologias de optimización de carga, y de seguridad contra ataques XSS, y SQL Injection." 
  - title: "Scripting"
    tags: ['bash', 'awk', 'sed', 'powershell']
    description: "Conocimientos en scripting, en sistemas Linux y Windows" 

##################
# Contact layout #
##################

email: "ggallohernandez@gmail.com"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "http://facebook.com/luisguillermogallohernandez"
  - title: "github"
    url: "https://github.com/ggallohernandez"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post

pages_list:
  Acerca de mi: 'acerca-de-mi'
  # Blog: 'blog'
  Experiencia: 'experiencia'
  Estudios: 'estudios'
  Contacto: 'contacto'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]
